services:
  postgres:
    image: postgres:15-alpine
    container_name: employee-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: employeedb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web

  backend:
    build: ./backend
    container_name: employee-backend
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: password123
      DB_NAME: employeedb
      PORT: 5000
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - web

  frontend:
    build: .
    container_name: employee-frontend
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-alche-staff-attendance.rule=Host(`attendance.alu.app`)"
      - "traefik.http.routers.frontend-alche-staff-attendance.service=frontend-alche-staff-attendance"
      - "traefik.http.routers.frontend-alche-staff-attendance.tls=true"
      - "traefik.http.routers.frontend-alche-staff-attendance.entrypoints=web,websecure"
      - "traefik.http.routers.frontend-alche-staff-attendance.tls.certresolver=le"
    networks:
      - web
volumes:
  pgdata:
networks: #using the traefk default network
  web:
    name: dockertraefk_default
    external: true
  postgres_data:
